[base]
mu = 1.5e-8
r = TruncatedExponential(a = 1e-8, b = 1e-6, lam = 4641167.677653745)
L = 20000
ploidy = 1

[samples]
# A diploid population with a variable size history defined by a spline
pop1 = {'N0': 'UniformFloatDiscrete([1e3, 2e3, 5e3, 1e4, 2e4, 5e4])', 'n': 50}


